apiVersion: v1
kind: Service
metadata:
  name: educational-app
spec:
  selector:
    app: educational-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 84
      nodePort: 30008
