apiVersion: v1
kind: Service
metadata:
  name: consultancy-website
spec:
  selector:
    app: consultancy-website
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 82
      nodePort: 30007
