apiVersion: apps/v1
kind: Deployment
metadata:
  name: educational-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: educational-app
  template:
    metadata:
      labels:
        app: educational-app
    spec:
      containers:
        - name: educational-app-container
          image: ajaydabe/edu.app:v3
          ports:
            - containerPort: 84
